### ISSUE TITLE
Use winston functions

### ISSUE THREAD

**Issue by RemyLespagnol** [pay-k/nestjs-winston#3]
Hello Guys!

How do you do to call profiling function on this logger ? (https://github.com/winstonjs/winston#profiling), I need that for my project, but I cannot achieve it..

Do you have a solution?

Thank you

**Comment by danshapir** [comment]
Hey,

I'll look into it and find a solution for you in the coming days, probably by Sunday.

Thanks,
Dan

**Comment by RemyLespagnol** [comment]
Thank you :)

I want to use it like this : `const logger = new Logger('AppModule')` where Logger can be an another class if needed.

Thanks,
Rémy

**Comment by danshapir** [comment]
Hey,

First of all please don't use new Logger, use 
`new WinstonLogger`

This allows using the internal logger service, but not losing the better meta handling of Winston.

To get the internal winston instance I have exposed it through dependency injection:
`@Inject(WINSTON_MODULE_PROVIDER) private readonly winston`
This will get you the internal winston logger instance that has all the internal functions such as profile.

No need to update anything already available.

**Comment by RemyLespagnol** [comment]
Yup I see the point :)
Thank you !
